import './globals.css';
import { SiteWrapper } from './site-wrapper';

/**
 * Using force dynamic so changes in business assets (e.g. services) are immediately reflected.
 * If you prefer having it reflected only after redeploy (not recommended) please remove it
 * **/
export const revalidate = 0;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Wix Events Site</title>
        <meta
          name="description"
          content="Generated by create next app with Wix Events integration"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://www.wix.com/favicon.ico" />
      </head>
      <body className="text-black bg-site">
        <SiteWrapper>{children}</SiteWrapper>
      </body>
    </html>
  );
}
